"""empty message

Revision ID: ff260dd71f1d
Revises: 
Create Date: 2017-12-05 19:28:46.663509

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ff260dd71f1d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('manufacturer',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.String(length=45), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('type',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.String(length=45), nullable=True),
    sa.Column('price', sa.INTEGER(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('login', sa.String(length=80), nullable=True),
    sa.Column('password', sa.String(length=80), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('username', sa.String(length=80), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('login'),
    sa.UniqueConstraint('password'),
    sa.UniqueConstraint('username')
    )
    op.create_table('sort',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.String(length=45), nullable=True),
    sa.Column('types_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['types_id'], ['type.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('complect',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('sort_id', sa.INTEGER(), nullable=True),
    sa.Column('manufacturer_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['manufacturer_id'], ['manufacturer.id'], ),
    sa.ForeignKeyConstraint(['sort_id'], ['sort.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('application_receipt',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('complect_id', sa.INTEGER(), nullable=True),
    sa.Column('quantity', sa.INTEGER(), nullable=True),
    sa.Column('date_adoption', sa.Date(), nullable=True),
    sa.Column('date_issue', sa.Date(), nullable=True),
    sa.Column('provider_id', sa.INTEGER(), nullable=True),
    sa.Column('price', sa.INTEGER(), nullable=True),
    sa.Column('confirmed', sa.BOOLEAN(), nullable=True),
    sa.ForeignKeyConstraint(['complect_id'], ['complect.id'], ),
    sa.ForeignKeyConstraint(['provider_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sklad',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('application_id', sa.INTEGER(), nullable=True),
    sa.Column('issued', sa.BOOLEAN(), nullable=True),
    sa.ForeignKeyConstraint(['application_id'], ['application_receipt.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sklad')
    op.drop_table('application_receipt')
    op.drop_table('complect')
    op.drop_table('sort')
    op.drop_table('user')
    op.drop_table('type')
    op.drop_table('manufacturer')
    # ### end Alembic commands ###
